/* DO NOT EDIT THIS FILE - it is machine generated */
#include "JNIConverter.h"
/* Header for class com_seewo_ns_NoiseSuppression */

#ifndef _Included_com_seewo_ns_NoiseSuppression
#define _Included_com_seewo_ns_NoiseSuppression
#ifdef __cplusplus
extern "C" {
#endif
    JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved);

    /*
    * Class:     com_seewo_ns_NoiseSuppression
    * Method:    WebRtcNsCreate
    * Signature: ()J
    */
    JNIEXPORT jlong JNICALL Java_com_seewo_ns_NoiseSuppression_WebRtcNsCreate
    (JNIEnv *, jclass);

      /*
    * Class:     com_seewo_ns_NoiseSuppression
    * Method:    WebRtcNsFree
    * Signature: (J)V
    */
    JNIEXPORT void JNICALL Java_com_seewo_ns_NoiseSuppression_WebRtcNsFree
    (JNIEnv *, jclass, jlong nsHandler);

    /*
    * Class:     com_seewo_ns_NoiseSuppression
    * Method:    WebRtcNsInit
    * Signature: (JI)I
    */
    JNIEXPORT jint JNICALL Java_com_seewo_ns_NoiseSuppression_WebRtcNsInit
    (JNIEnv *, jclass, jlong nsHandler, jint sf);

    /*
    * Class:     com_seewo_ns_NoiseSuppression
    * Method:    WebRtcNsSetPolicy
    * Signature: (JI)I
    */
    JNIEXPORT jint JNICALL Java_com_seewo_ns_NoiseSuppression_WebRtcNsSetPolicy
    (JNIEnv *, jclass, jlong nsHandler, jint mode);




#ifdef __cplusplus
}
#endif
#endif
